### ISSUE TITLE
Document downsides of running against output of Spark < 1.2.1

### ISSUE THREAD

**Issue by tpanningnextcen** [kayousterhout/trace-analysis#3]
The README says that this script was designed to run on the output of Spark 1.2.1 or later. But I also saw that there is a commit that adds support for parsing logs from before 1.2.0. I remember from your O'Reilly webcast that you worked to get more/better metrics added in 1.2.1, so I'm assuming that's why the tool was designed for 1.2.1. or later.

Can you document the caveats that should users be aware of if they run this on earlier versions? Will there be time spent that isn't included in the measurements, or is some time mis-categorized, or is it something else? You've already provided helpful documentation on some ongoing mis-categorization  (i.e., time spent reading/writing from/to HDFS will be called "compute").

I'm asking because this tool provides a valuable way to look at a job's performance, but I'm running against Spark 1.2.0 and I want to know if there are things I should be aware of.

**Comment by joeschmid** [comment]
+1 We're running Spark via Datastax Enterprise. The current DSE version 4.6 is still on (yikes!) Spark 1.1.0. (Also, thanks Kay for this great tool -- this will be hugely helpful!)

**Comment by kayousterhout** [comment]
I added documentation for this! The original reason I wrote that the tool was designed for 1.2.1 was because it would crash on earlier Spark versions, but as you mentioned, I fixed that problem with a more recent commit.
